#coding:utf8
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
fiblist = [1,2]
def fib(n,l):
    tmp = l[-1] + l[-2]
    if tmp > n:
        return
    l.append(tmp)
    fib(n, l)

fib(4000000, fiblist)

print sum([n for n in fiblist if n%2==0])
